// ui/ui-editors/src/app/editor/_components/common/code-editor.component.ts
/**
 * @license
 * Copyright 2017 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, EventEmitter, Input, Output, ViewChild, ViewEncapsulation} from "@angular/core";
import {AceEditorComponent} from "./ace-editor.component";
import {Debouncer} from "apicurio-ts-core";


export enum CodeEditorTheme {
    Light, Dark
}

export enum CodeEditorMode {
    Text, JSON, YAML, Markdown, XML, GRAPHQL
}

@Component({
    selector: "code-editor",
    templateUrl: "code-editor.component.html",
    encapsulation: ViewEncapsulation.None
})
export class CodeEditorComponent {

    private static DEFAULT_DEBOUNCE_TIME: number = 200;

    @ViewChild("editor", { static: true }) public editor: AceEditorComponent;

    private _textValueDebouncer: Debouncer<string> = new Debouncer<string>({ period: 200 }, value => {
        this.textChange.emit(value);
    });

    @Input() theme: CodeEditorTheme = CodeEditorTheme.Light;
    @Input() mode: CodeEditorMode = CodeEditorMode.Text;
    @Input() editorStyle: any;
    @Input() wordWrap: boolean = false;

    @Input()
    get text() {
        return this._textValueDebouncer.getValue();
    }

    @Output() public textChange = new EventEmitter<string>();
    set text(value: string) {
        this._textValueDebouncer.emit(value);
    }

    @Input()
    get debounceTime() {
        return this._textValueDebouncer["options"].period;
    }
    set debounceTime(time: number) {
        let bounce: number = time;
        if (!bounce) {
            bounce = CodeEditorComponent.DEFAULT_DEBOUNCE_TIME;
        }
        this._textValueDebouncer["options"].period = bounce;
    }

    public aceMode(): string {
        switch (this.mode) {
            case CodeEditorMode.YAML:
                return 'yaml';
            case CodeEditorMode.JSON:
                return 'json';
            case CodeEditorMode.Text:
                return 'text';
            case CodeEditorMode.XML:
                return 'xml';
            case CodeEditorMode.Markdown:
                return 'markdown';
            case CodeEditorMode.GRAPHQL:
                return 'graphqlschema';
            default:
                return 'text';
        }
    }

    public aceTheme(): string {
        if (this.theme === CodeEditorTheme.Dark) {
            return "twilight";
        } else {
            return "eclipse";
        }
    }

    public focus(): void {
        this.editor.focus();
    }

    public setText(text: string): void {
        this.editor.setText(text);
    }
}

<ace-editor #editor
            [theme]="aceTheme()"
            [mode]="aceMode()"
            [(text)]="text"
            [wordWrap]="wordWrap"
            [ngStyle]="editorStyle"></ace-editor>

// ui-rhosr/src/app/pages/editor/components/code-editor.tsx
/**
 * @license
 * Copyright 2022 Red Hat
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import React, { PureComponent } from "react";
import Editor from "@monaco-editor/react";
import { PureComponentProps, PureComponentState } from "src/app";
import { Services } from "src/services";

export interface CodeEditorProps extends PureComponentProps {
	content: string | null
  	onChange: (newContent: string ) => void
	language: string | undefined
}

export interface CodeEditorState extends PureComponentState {
	content: string
}

export class CodeEditor extends PureComponent<CodeEditorProps, CodeEditorState> {
	protected initializeState(): CodeEditorState {
	  return {
		content: this.props.content as string
	  };
	}
  
	constructor(props: Readonly<CodeEditorProps>) {
		super(props);
	}

	public componentDidMount() {
		Services.getLoggerService().debug("[CodeEditor] Component did MOUNT.");
	}
  
	public componentDidUpdate(prevProps: Readonly<CodeEditorProps>, _prevState: Readonly<CodeEditorState>, _snapshot?: {}) {
		Services.getLoggerService().debug("[CodeEditor] Component did UPDATE -- previous props: ", prevProps);
	}

	render(): React.ReactElement {
		return <Editor
			height="100vh"
			defaultLanguage={getArtifactLanguage(this.props.language)}
			defaultValue={ this.props.content as string }
			onChange={(value) => this.props.onChange(value as string)}
		/>
	}
}

// maps the artifact type to the associated language type from the editor
const getArtifactLanguage = (artifactType: string | undefined): string => {
	if (artifactType == undefined) {
		return textLanguage;
	}
	const language = artifactTypeMonacoLanguageMap[artifactType];

	return language || textLanguage;
}

const jsonLanguage = 'json';
const xmlLanguage = 'xml';
const textLanguage = 'text';

const artifactTypeMonacoLanguageMap: {[key: string]: string} = {
	'XML': xmlLanguage,
	'GRAPHQL': 'graphql',
	'AVRO': jsonLanguage,
	'WSDL': xmlLanguage,
	'XSD': xmlLanguage,
	'PROTOBUF': textLanguage,
	'KCONNECT': textLanguage
}
